name: "isignal"
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  pulsator: ^1.0.0+2
  flutter_launcher_icons: ^0.13.1
  flutter_otp_text_field: ^1.1.3+2
  flutter_screenutil: ^5.9.0
  provider: ^6.0.5
  http: ^1.1.0
  awesome_dialog: ^3.2.1

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/logo/app-logo.png"
  image_path: "assets/images/logo/app-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo/
    - assets/json/
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  fonts:
    - family: AnkhSanctuary
      fonts:
        - asset: assets/fonts/AnkhSanctuary-PVK0B.ttf
          weight: 700
    - family: Din
      fonts:
        - asset: assets/fonts/DIN-BlackAlternate.ttf
        - asset: assets/fonts/DIN-Bold.ttf
        - asset: assets/fonts/DIN-Light.ttf
        - asset: assets/fonts/DIN-Medium.ttf
        - asset: assets/fonts/DIN-RegularAlternate.ttf
        - asset: assets/fonts/DIN-Regular.ttf

          weight: 700
          

  
  # AnkhSanctuary-PVK0B
